# Logical Function (AND , OR & XOR)

In the below program I am trying to achieve the basic Logical AND , OR & XOR operation using Neural Network.

In [1]:
# Loading the libraries


import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

import seaborn as sns
sns.set()

from scipy import optimize
from ipywidgets import *
from IPython.display import SVG
from sklearn import datasets

In [35]:
# Constructing the AND function

AND = pd.DataFrame({'x1': (0,0,1,1), 'x2': (0,1,0,1), 'y': (0,0,0,1)})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [36]:
# At very first,I initialize weights to small, random values (can be positive and negative).

w = np.random.randn(3)*1e-4

In [37]:
print(w)

[-1.74454421e-04  2.15302370e-05 -2.12050814e-05]


In [38]:
# A simple Activation Function

g = lambda inputs, weights: np.where(np.dot(inputs, weights)>0, 1, 0)

In [39]:
# Finally , a training function that iterates the learning algorithm, returning the adapted weights.

def train(inputs, targets, weights, eta, n_iterations):

    # Add the inputs that match the bias node
    inputs = np.c_[inputs, -np.ones((len(inputs), 1))]

    for n in range(n_iterations):

        activations = g(inputs, weights);
        weights -= eta*np.dot(np.transpose(inputs), activations - targets)
        print('The iteration is',n,' The weight is ',weights)
        
    return(weights)

In [40]:
# Testing it first on the AND function.
# Here learning rate is 0.25 and number of epoch is 10
inputs = AND[['x1','x2']]
target = AND['y']

w = train(inputs, target, w, 0.25,10)

The iteration is 0  The weight is  [2.49825546e-01 2.15302370e-05 2.49978795e-01]
The iteration is 1  The weight is  [ 4.99825546e-01  2.50021530e-01 -2.12050814e-05]
The iteration is 2  The weight is  [2.49825546e-01 2.15302370e-05 7.49978795e-01]
The iteration is 3  The weight is  [0.49982555 0.25002153 0.49997879]
The iteration is 4  The weight is  [0.49982555 0.25002153 0.49997879]
The iteration is 5  The weight is  [0.49982555 0.25002153 0.49997879]
The iteration is 6  The weight is  [0.49982555 0.25002153 0.49997879]
The iteration is 7  The weight is  [0.49982555 0.25002153 0.49997879]
The iteration is 8  The weight is  [0.49982555 0.25002153 0.49997879]
The iteration is 9  The weight is  [0.49982555 0.25002153 0.49997879]


In [41]:
# Updated weights

print(w)

[0.49982555 0.25002153 0.49997879]


In [42]:
# Checking the performance

g(np.c_[inputs, -np.ones((len(inputs), 1))], w)

array([0, 0, 0, 1])

In [10]:
# Testing it for OR function
OR = pd.DataFrame({'x1': (0,0,1,1), 'x2': (0,1,0,1), 'y': (0,1,1,1)})
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [11]:
w_OR = np.random.randn(3)*1e-4

In [12]:
print(w_OR)

[-8.60058817e-05 -1.04782991e-04  1.25649518e-04]


In [13]:
inputs_OR = OR[['x1','x2']]
target_OR = OR['y']

w_OR = train(inputs_OR, target_OR, w_OR, 0.25, 20)

In [14]:
print(w_OR)

[4.99913994e-01 4.99895217e-01 1.25649518e-04]


In [15]:
g(np.c_[inputs_OR, -np.ones((len(inputs_OR), 1))], w_OR)

array([0, 1, 1, 1])

In [43]:
# Testing it for XOR function
XOR = pd.DataFrame({'x1': (0,0,1,1), 'x2': (0,1,0,1), 'y': (0,1,1,0)})
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [44]:
w_XOR = np.random.randn(3)*1e-4

In [45]:
print(w_XOR)

[ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]


In [46]:
inputs_XOR = XOR[['x1','x2']]
target_XOR = XOR['y']

w_XOR = train(inputs_XOR, target_XOR, w_XOR, 0.25, 20)

The iteration is 0  The weight is  [-0.2499366  -0.24996113  0.49998726]
The iteration is 1  The weight is  [ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]
The iteration is 2  The weight is  [-0.2499366  -0.24996113  0.49998726]
The iteration is 3  The weight is  [ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]
The iteration is 4  The weight is  [-0.2499366  -0.24996113  0.49998726]
The iteration is 5  The weight is  [ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]
The iteration is 6  The weight is  [-0.2499366  -0.24996113  0.49998726]
The iteration is 7  The weight is  [ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]
The iteration is 8  The weight is  [-0.2499366  -0.24996113  0.49998726]
The iteration is 9  The weight is  [ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]
The iteration is 10  The weight is  [-0.2499366  -0.24996113  0.49998726]
The iteration is 11  The weight is  [ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]
The iteration is 12  The weight is  [-0.2499366  -

In [47]:
print(w_XOR)

[ 6.34022719e-05  3.88685893e-05 -1.27433300e-05]


In [51]:
g(np.c_[inputs_XOR, -np.ones((len(inputs_XOR), 1))], w_XOR)

array([1, 1, 1, 1])

Clearly, for the XOR function, the output classes are not linearly separable. So, the algorithm does not converge on an answer, but simply cycles through two incorrect solutions.